# Site settings
title: Knightstart - HTML5 Gruntjs Boilerplate
email: eugenemutai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   HTML5 starter kit for creating HTML5 application and user interfaces, with GRUNTJS integration for fast, clean and optimized app creation.
baseurl: "/knightstart" # the subpath of your site, e.g. /blog/
url: "http://jheneknights.github.io/knightstart/" # the base hostname & protocol for your site

twitter_username: jheneknights
github_username:  jheneknights

# Build settings
markdown: kramdown
highlighter: pygments
github: [Repository metadata]

# site stuff
tar_url: "https://github.com/jheneknights/knightstart/tarball/master"
zip_url: "https://github.com/jheneknights/knightstart/zipball/master"
project_url: "https://github.com/jheneknights/knightstart"